### ISSUE TITLE
Update to new semantic?

### ISSUE THREAD

**Issue by gapipro** [vueui/vue-ui#1]
Hi,

will you continue to develop/upgrade this lib or has development ended?

**Comment by agonbina** [comment]
Hey sorry for the delay. Initially I started this project to remove the jQuery dependency from Semantic UI but after implementing a few components, it turned out to be a difficult task to remove jQuery and still carry over all of the functionality of a Semantic UI component(with its jQuery implementation)

Currently I am using only a few components from Semantic UI so I have no immediate plans to implement all of them in Vue.js. Maybe in the future If i find some free time this will change :)

**Comment by gapipro** [comment]
Ok, thank you =)
